NTP_servers:
  hostnames_or_ip_addresses: null

backup_to_ftp_servers:
  - hostname: server1
    username: Controller
    password: FtpController123@
    port: 22
    isActive: true
  - hostname: server2
    username: Controller
    password: FtpController123@
    port: 22
    isActive: false
Rsyslog_server:
  hostnames_or_ip_addresses: null
