---
- name: Run health check commands from script
  cisco.ios.ios_command:
    commands: "{{ lookup('file', role_path + '/scripts/Cisco_Equipement_HC.txt').splitlines() | select('match', '^[^!].*') }}"
  register: hc_results

- name: Save script output to a local file
  ansible.builtin.copy:
    content: "{{ hc_results }}"
    dest: "{{ role_path }}/../tmp/logs/{{ inventory_hostname }}_health_check_{{ date.utctime('%Y%m%d_%H%M%S') }}.log"
  delegate_to: localhost