---
- name: Set timestamp for log files
  ansible.builtin.set_fact:
    log_timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    # Using ansible.builtin.now() filter is more portable and Ansible-native
    # log_timestamp: "{{ ansible.builtin.now().strftime('%Y%m%d_%H%M%S') }}"
  delegate_to: localhost
  run_once: true # Ensure this task runs only once on the control node

- name: Run health check commands from script
  cisco.ios.ios_command:
    commands: "{{ lookup('template', 'Cisco_Equipement_HC.j2').splitlines() | select('match', '^[^!].*') }}"
  register: hc_results

- name: Ensure log directory exists on the Ansible controller
  ansible.builtin.file:
    path: "{{ playbook_dir }}/tmp/logs"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Save formatted health check output to a local file
  ansible.builtin.copy:
    content: |
      {% for item in hc_results.results -%}
      #################################################################
      ### COMMAND: {{ item.item }}
      #################################################################
      {{ item.stdout | default('No output') }}

      {% endfor %}
    dest: "{{ playbook_dir }}/tmp/logs/{{ inventory_hostname }}_health_check_{{ log_timestamp }}.log"
  delegate_to: localhost