- name: backup Cisco node
  hosts: Cisco
  gather_facts: no
  tasks:
    - name: backup Cisco node
      ios_command:
        commands: show run
      register: output

    - name: Save config to local file
      ansible.builtin.copy:
        content: "{{ output.stdout_lines | join('\n') }}"
        dest: "{{ playbook_dir }}/../tmp/backup/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
      delegate_to: localhost

#- name: Backup Linux nodes