- name: nodes Health check
  hosts: all
  gather_facts: no
  tasks:

    - name: Run health check commands from script
      cisco.ios.ios_command:
        commands: "{{ lookup('template', 'Cisco_Equipement_HC.j2').splitlines() | select('match', '^[^!].*') }}"
        register: hc_results
        when: ansible_network_os == 'ios'

    - name: HC for Linux system
      shell:
        cmd: "{{ lookup('template', 'Linux_HC.j2').splitlines() | select('match', '^[^!].*') }}"
      register: hc_results
      when: false

    - name: debug msg
      debug:
        msg: "{{ hc_results.stdout_lines }}"

    - name: Save formatted health check output to a local file
      ansible.builtin.copy:
        content: "{{ hc_results.stdout_lines }}"
        dest: "{{ playbook_dir }}/../tmp/logs/{{ inventory_hostname }}_health_check_{{ ansible.builtin.now().strftime('%Y%m%d_%H%M%S') }}.log"
        delegate_to: localhost
