- name: Backup Nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: backup Cisco node
      ios_command:
        commands: show run
      register: output
      when: ansible_network_os == 'ios'

    - name: debug
      debug:
       msg: "{{ output }}"

    - name: Save config to local file
      ansible.builtin.copy:
        content: "{{ output.stdout_lines | join('\n') }}"
        dest: "{{ playbook_dir }}/../tmp/backup/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
      delegate_to: localhost

#- name: Backup Linux nodes