- name: Secure switch ports with Ansible
  hosts: SW1
  gather_facts: no

  tasks:
    - name: list all working interfaces
      cisco.ios.ios_command:
        commands:
          - show ip interface brief | include up
      register: interfaces


    - name: LIST interfaces
      debug:
        msg: >-
          
          {% for data in interfaces.stdout_lines %}
          {% set interface_names = data | map('split') | map('first') | list %}
          {% endfor %}         
          
          
          {{ interface_names }} 
          
