- name: Secure switch ports with Ansible
  hosts: SW1
  gather_facts: no

  tasks:
    - name: list all working interfaces
      cisco.ios.ios_command:
        commands:
          - show ip interface brief | include up
      register: interfaces

    - name: Extract interface names
      set_fact:
        interface_names: "{{ interfaces.stdout_lines[0] | map('split') | map('first') | list }}"

    - name: Show interface names
      debug:
        msg: "{{ interface_names }}"