#Test playbook
---
- name: Backup
  hosts: all
  gather_facts: no
  roles:
    - common

  tasks:
    - name: test connection
      include_tasks: "roles/common/tasks/test_connectivity.yml"
    - name: test Commands
      ios_command:
        commands:
          - show ip int br
          - show arp
        when: ansible_network_os == 'ios'
        register: output

    - name: print register variable
      debug:
        msg: output

